# Generated by Django 4.2.1 on 2023-07-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='dedscricao',
            new_name='descricao',
        ),
    ]
